title: Pietro Soglia
logo: /assets/img/profile.png
description: I am a Data Scientist and AI Engineer working in tech
theme: jekyll-theme-minimal
show_downloads: True
github:
  zip_url: https://drive.google.com/file/d/15tcSTV2M2tdrZcmC3hXjIJyiLEiZ7fTx/view?usp=sharing
  tar_url: https://drive.google.com/file/d/1KB6ZuzqTP251bNht0Q5qD2CRtiH3djh0/view?usp=sharing
  is_project_page: False
