title: Pietro Soglia
logo: /assets/img/profile.png
description: text
theme: jekyll-theme-minimal
show_downloads: True
github:
  zip_url: https://drive.google.com/file/d/1yRDxJQFXqL0KDAbS7uBEiT9vUtrlyaAn/view?usp=sharing
  tar_url: https://drive.google.com/file/d/1MRUF-N9avkVNa18zmeY2GrZHWvgIW-N4/view?usp=sharing
  repository_url: https://www.linkedin.com/in/pietro-soglia-97477b217/
